site_name: Resolos
theme: readthedocs
nav:
  - Home: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Managing remotes: remotes.md
  - Creating projects: projects.md
  - Working with projects: work_with_projects.md
  - Archival: archive.md
  - Commands: commands.md


markdown_extensions:
  - mkdocs-click
  - attr_list