name: Test for pull requests

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]

jobs:
  ubuntu:
    name: Run pytest on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Pull and checkout branch
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          wget https://github.com/bcpierce00/unison/releases/download/v2.53.3/unison-2.53.3-ubuntu-x86_64-static.tar.gz && mkdir -p ~/bin && tar -xf unison-2.53.3-ubuntu-x86_64-static.tar.gz bin/unison && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          pip install -r requirements.txt

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.8

      - name: Run test suite
        run: |
          echo "Adding unison to path" && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          echo "Conda version is $(conda --version)"
          pytest --ignore=tests/integration/
  macos:
    name: Run pytest on macos-latest
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Pull and checkout branch
        uses: actions/checkout@master

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          auto-activate-base: false
          python-version: 3.8

      - name: Install dependencies
        run: |
          echo "Installing unison"
          wget https://github.com/bcpierce00/unison/releases/download/v2.53.3/unison-2.53.3-macos-x86_64.tar.gz && mkdir -p ~/bin && tar -xf unison-2.53.3-macos-x86_64.tar.gz bin/unison && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          echo "Installing dependencies into test environment"
          conda activate test
          conda env list
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          echo "Adding unison to path" && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          echo "Activating test environment"
          conda activate test
          echo "Conda version is $(conda --version)"
          pytest --ignore=tests/integration/