name: Test for pull requests

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Pull and checkout branch
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          wget https://github.com/bcpierce00/unison/releases/download/v2.51.3/unison-v2.51.3+ocaml-4.10.0+x86_64.linux.static.tar.gz && mkdir -p ~/bin && tar -xf unison-v2.51.3+ocaml-4.10.0+x86_64.linux.static.tar.gz bin/unison && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          pytest

