name: Integration test with SLURM run manually

on:
  push:
      branches:
        - salid/integration-test
jobs:
  ubuntu:
    name: Run pytest on ubuntu-latest
    runs-on: ubuntu-latest
    env:
      TEST_USER: testuser
      SSHPASS: ${{ secrets.TEST_PASSWORD }}}
      
      
    steps:
      - name: Pull and checkout branch
        uses: actions/checkout@master

      - name: Setup SLURM-in-docker cluster
        run: |
          sudo apt-get install sshpass
          docker-compose -f tests/integration/docker-compose.yaml up -d
          sleep 20
          export pass=$(perl -e 'print crypt($ARGV[0], "password")' "$SSHPASS")
          docker exec slurmctld bash -c 'useradd -m -p "$0" "$1"' "$pass" "$TEST_USER"
          docker exec c1 bash -c 'useradd -m -p "$0" "$1"' "$pass" "$TEST_USER"
          docker exec c2 bash -c 'useradd -m -p "$0" "$1"' "$pass" "$TEST_USER"
          docker exec slurmctld bash -c 'chmod -R 777 /data'
          docker exec slurmctld bash -c "/usr/bin/sacctmgr --immediate add cluster name=linux"
          docker-compose -f tests/integration/docker-compose.yaml restart slurmdbd slurmctld
          docker exec slurmctld bash -c 'sacctmgr -i add account "$0" cluster=linux description="Resolos integration test user" Organization=resolos' $TEST_USER
          docker exec slurmctld bash -c 'sacctmgr -i add user "$0" account="$0"' $TEST_USER $TEST_USER

      - name: Install dependencies
        run: |
          wget https://github.com/bcpierce00/unison/releases/download/v2.51.3/unison-v2.51.3+ocaml-4.10.0+x86_64.linux.static.tar.gz && mkdir -p ~/bin && tar -xf unison-v2.51.3+ocaml-4.10.0+x86_64.linux.static.tar.gz bin/unison && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          pip install -r requirements.txt

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.8

      - name: Run test suite
        run: |
          export TEST_HOST=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' slurmctld)
          ssh-keyscan -H $TEST_HOST >> ~/.ssh/known_hosts
          rm -f $HOME/.ssh/id_rsa_resolos
          rm -f $HOME/.ssh/id_rsa_resolos.pub
          echo "Adding unison to path" && export PATH="$(pwd)/bin:$PATH"
          echo "Unison installed at: $(which unison)"
          echo "Conda version is $(conda --version)"
          pytest tests/integration/test_integration.py

      - name: Tear down SLURM cluster
        run: |
          docker-compose -f tests/integration/docker-compose.yaml down -v --rmi local

